/**
 * Theme (accent color) + Template (layout) system.
 *
 * Themes own the corporate accent palette (White backgrounds with Red, Green,
 * or Navy/Black accents). Templates own the layout structure (bordered cards,
 * banner header, grid lines, etc.). `buildPalette(theme, template)` resolves
 * both into the single style object PosterCanvas renders with.
 */

/* ─────────────────────────── Themes (accent colors) ─────────────────────────── */

export const THEMES = [
  {
    id: "navy",
    name: "Classic Navy & White",
    accent: "#1e40af",
    accentDark: "#172554",
    accentLight: "#3b82f6",
    accentSoft: "#eef2ff",
    accentBorder: "#c7d2fe",
    onAccent: "#ffffff",
    bandGradient: "linear-gradient(90deg, #172554, #1e40af 55%, #3b82f6)",
    ctaGradient: "linear-gradient(135deg, #172554, #1e40af)",
    markerA: "#1e40af",
    markerB: "#3b82f6",
    title: "#0f172a",
    body: "#334155",
    label: "#64748b",
    value: "#0f172a",
    sectionHeader: "#0f172a",
    cardBg: "#ffffff",
    cardBorder: "#e2e8f0",
    chipBg: "#eef2ff",
    chipBorder: "#c7d2fe",
    chipText: "#1e40af",
    tileA: "linear-gradient(135deg, #172554, #1e40af)",
    tileAIcon: "#ffffff",
    tileB: "#eef2ff",
    tileBBorder: "#c7d2fe",
    tileBIcon: "#1e40af",
    footerAccent: "#1e40af",
    bgSoft: "#f4f7fd",
    bgColor: "#ffffff",
    bg: "linear-gradient(180deg, #ffffff 0%, #f4f7fd 100%)",
    dots: "rgba(30,58,138,0.06)",
    glowA: "rgba(37,99,235,0.10)",
    glowB: "rgba(30,58,138,0.08)",
    badgeBg: "#1e40af",
    badgeText: "#ffffff",
    pleaseNoteBg: "#eef2ff",
    pleaseNoteText: "#1e40af",
    ecoIconBg: "#eef2ff",
    ecoIcon: "#1e40af",
    ecoLabel: "#475569",
    infoBg: "#ffffff",
    infoBorder: "#e2e8f0",
    infoShadow: "0 8px 24px rgba(15,42,92,0.06)",
    cardShadow: "0 10px 30px rgba(15,42,92,0.06)",
    ctaSoft: "rgba(255,255,255,0.15)",
    ctaSoftBorder: "rgba(255,255,255,0.4)",
  },
  {
    id: "red",
    name: "Bold Executive Red & White",
    accent: "#dc2626",
    accentDark: "#991b1b",
    accentLight: "#f87171",
    accentSoft: "#fee2e2",
    accentBorder: "#fecaca",
    onAccent: "#ffffff",
    bandGradient: "linear-gradient(90deg, #991b1b, #dc2626 55%, #f87171)",
    ctaGradient: "linear-gradient(135deg, #991b1b, #dc2626)",
    markerA: "#dc2626",
    markerB: "#ef4444",
    title: "#1c1917",
    body: "#44403c",
    label: "#78716c",
    value: "#1c1917",
    sectionHeader: "#1c1917",
    cardBg: "#ffffff",
    cardBorder: "#e7e5e4",
    chipBg: "#fee2e2",
    chipBorder: "#fecaca",
    chipText: "#b91c1c",
    tileA: "linear-gradient(135deg, #991b1b, #dc2626)",
    tileAIcon: "#ffffff",
    tileB: "#fee2e2",
    tileBBorder: "#fecaca",
    tileBIcon: "#dc2626",
    footerAccent: "#b91c1c",
    bgSoft: "#fdf6f6",
    bgColor: "#ffffff",
    bg: "linear-gradient(180deg, #ffffff 0%, #fdf6f6 100%)",
    dots: "rgba(185,28,28,0.06)",
    glowA: "rgba(220,38,38,0.08)",
    glowB: "rgba(153,27,27,0.06)",
    badgeBg: "#dc2626",
    badgeText: "#ffffff",
    pleaseNoteBg: "#fee2e2",
    pleaseNoteText: "#b91c1c",
    ecoIconBg: "#fee2e2",
    ecoIcon: "#dc2626",
    ecoLabel: "#57534e",
    infoBg: "#ffffff",
    infoBorder: "#e7e5e4",
    infoShadow: "0 8px 24px rgba(153,27,27,0.06)",
    cardShadow: "0 10px 30px rgba(153,27,27,0.06)",
    ctaSoft: "rgba(255,255,255,0.15)",
    ctaSoftBorder: "rgba(255,255,255,0.4)",
  },
  {
    id: "green",
    name: "Vibrant Forest Green & White",
    accent: "#15803d",
    accentDark: "#14532d",
    accentLight: "#4ade80",
    accentSoft: "#dcfce7",
    accentBorder: "#bbf7d0",
    onAccent: "#ffffff",
    bandGradient: "linear-gradient(90deg, #14532d, #15803d 55%, #4ade80)",
    ctaGradient: "linear-gradient(135deg, #14532d, #15803d)",
    markerA: "#15803d",
    markerB: "#22c55e",
    title: "#111827",
    body: "#374151",
    label: "#6b7280",
    value: "#111827",
    sectionHeader: "#111827",
    cardBg: "#ffffff",
    cardBorder: "#e5e7eb",
    chipBg: "#dcfce7",
    chipBorder: "#bbf7d0",
    chipText: "#15803d",
    tileA: "linear-gradient(135deg, #14532d, #15803d)",
    tileAIcon: "#ffffff",
    tileB: "#dcfce7",
    tileBBorder: "#bbf7d0",
    tileBIcon: "#15803d",
    footerAccent: "#15803d",
    bgSoft: "#f5fbf7",
    bgColor: "#ffffff",
    bg: "linear-gradient(180deg, #ffffff 0%, #f5fbf7 100%)",
    dots: "rgba(21,128,61,0.06)",
    glowA: "rgba(34,197,94,0.08)",
    glowB: "rgba(21,128,61,0.06)",
    badgeBg: "#15803d",
    badgeText: "#ffffff",
    pleaseNoteBg: "#dcfce7",
    pleaseNoteText: "#15803d",
    ecoIconBg: "#dcfce7",
    ecoIcon: "#15803d",
    ecoLabel: "#4b5563",
    infoBg: "#ffffff",
    infoBorder: "#e5e7eb",
    infoShadow: "0 8px 24px rgba(21,128,61,0.06)",
    cardShadow: "0 10px 30px rgba(21,128,61,0.06)",
    ctaSoft: "rgba(255,255,255,0.15)",
    ctaSoftBorder: "rgba(255,255,255,0.4)",
  },
  {
    id: "mono",
    name: "Sleek Black & White",
    accent: "#111111",
    accentDark: "#000000",
    accentLight: "#525252",
    accentSoft: "#f5f5f5",
    accentBorder: "#d4d4d4",
    onAccent: "#ffffff",
    bandGradient: "linear-gradient(90deg, #000000, #111111 55%, #3f3f3f)",
    ctaGradient: "linear-gradient(135deg, #000000, #262626)",
    markerA: "#111111",
    markerB: "#525252",
    title: "#0a0a0a",
    body: "#3f3f3f",
    label: "#71717a",
    value: "#0a0a0a",
    sectionHeader: "#0a0a0a",
    cardBg: "#ffffff",
    cardBorder: "#e5e5e5",
    chipBg: "#f5f5f5",
    chipBorder: "#d4d4d4",
    chipText: "#111111",
    tileA: "linear-gradient(135deg, #000000, #262626)",
    tileAIcon: "#ffffff",
    tileB: "#f5f5f5",
    tileBBorder: "#d4d4d4",
    tileBIcon: "#111111",
    footerAccent: "#111111",
    bgSoft: "#fafafa",
    bgColor: "#ffffff",
    bg: "linear-gradient(180deg, #ffffff 0%, #fafafa 100%)",
    dots: "rgba(0,0,0,0.05)",
    glowA: "rgba(0,0,0,0.05)",
    glowB: "rgba(0,0,0,0.04)",
    badgeBg: "#111111",
    badgeText: "#ffffff",
    pleaseNoteBg: "#f5f5f5",
    pleaseNoteText: "#111111",
    ecoIconBg: "#f5f5f5",
    ecoIcon: "#111111",
    ecoLabel: "#52525b",
    infoBg: "#ffffff",
    infoBorder: "#e5e5e5",
    infoShadow: "0 8px 24px rgba(0,0,0,0.06)",
    cardShadow: "0 10px 30px rgba(0,0,0,0.07)",
    ctaSoft: "rgba(255,255,255,0.15)",
    ctaSoftBorder: "rgba(255,255,255,0.35)",
  },
];

export const LAYOUTS = [
  { id: "split", name: "Side-by-Side 2-Column Grid" },
  { id: "stacked", name: "Stacked Full-Width Rows" },
];

export const DEFAULT_THEME_ID = "navy";

export function getTheme(id) {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

/* ─────────────────────────── Templates (layout) ─────────────────────────── */

export const TEMPLATES = [
  {
    id: "classic",
    name: "Classic Corporate",
    desc: "Bordered rounded cards on white",
    showTopBar: true,
    banner: false,
    borderless: false,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: false,
  },
  {
    id: "banner",
    name: "Split Header Banner",
    desc: "Colored header band bleeding to the edges",
    showTopBar: false,
    banner: true,
    borderless: false,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: false,
  },
  {
    id: "minimal",
    name: "Minimalist Grid",
    desc: "Thin borders, clean grid lines, flat",
    showTopBar: true,
    banner: false,
    borderless: false,
    gridLines: true,
    neon: false,
    dark: false,
    serifTitle: false,
  },
  {
    id: "executive",
    name: "Executive Serif",
    desc: "Serif title, soft tinted background",
    showTopBar: true,
    banner: false,
    borderless: false,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: true,
  },
  {
    id: "borderless",
    name: "Borderless Clean",
    desc: "Flat tinted sections, no borders",
    showTopBar: false,
    banner: false,
    borderless: true,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: false,
  },
  {
    id: "dark",
    name: "Modern Dark",
    desc: "Dark background with neon accents",
    showTopBar: true,
    banner: false,
    borderless: false,
    gridLines: false,
    neon: true,
    dark: true,
    serifTitle: false,
  },
  {
    id: "corporate",
    name: "Corporate EMC Flyer",
    desc: "EMC reference style — navy/red/green grading, red-border HIRING badge, green ribbon",
    showTopBar: false,
    banner: false,
    borderless: false,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: false,
    corporate: true,
  },
  {
    id: "hiring",
    name: "We're Hiring Ribbon",
    desc: "Flyer 7 style — light blue bg, angled charcoal HIRING ribbon, red title",
    showTopBar: false,
    banner: false,
    borderless: false,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: false,
    hiring: true,
  },
  {
    id: "darkcard",
    name: "Dark Poster Card",
    desc: "Flyer 6 style — dark green page with centered white content card",
    showTopBar: false,
    banner: false,
    borderless: false,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: false,
    darkCard: true,
  },
  {
    id: "splitdark",
    name: "Split Dark Header",
    desc: "Flyer 3 style — light field with navy diagonal split, logo on the dark side",
    showTopBar: false,
    banner: false,
    borderless: false,
    gridLines: false,
    neon: false,
    dark: false,
    serifTitle: false,
    splitDark: true,
  },
];

export const DEFAULT_TEMPLATE_ID = "classic";

export function getTemplate(id) {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

/* ─────────────────────────── Palette resolver ─────────────────────────── */

/**
 * Resolve a theme + template into the full style object PosterCanvas uses.
 * Templates start from the theme palette, then apply their layout overrides.
 */
export function buildPalette(themeId, templateId) {
  const theme = getTheme(themeId);
  const tpl = getTemplate(templateId);

  let t = { ...theme, ...tpl };

  if (tpl.dark) {
    t = {
      ...t,
      bgColor: "#0a0f1c",
      bg: "linear-gradient(180deg, #0a0f1c 0%, #0d1424 100%)",
      title: "#f8fafc",
      body: "#cbd5e1",
      label: "#64748b",
      value: "#f1f5f9",
      sectionHeader: "#e2e8f0",
      infoBg: "rgba(17,24,39,0.92)",
      infoBorder: "rgba(148,163,184,0.16)",
      cardBg: "rgba(17,24,39,0.92)",
      cardBorder: "rgba(148,163,184,0.16)",
      cardShadow: `0 14px 36px rgba(0,0,0,0.5), 0 0 0 1px ${theme.accentLight}14`,
      chipBg: `${theme.accentLight}14`,
      chipBorder: `${theme.accentLight}66`,
      chipText: "#e0f2fe",
      tileB: `${theme.accentLight}1f`,
      tileBBorder: `${theme.accentLight}80`,
      tileBIcon: theme.accentLight,
      markerA: theme.accentLight,
      markerB: theme.accentLight,
      dots: "rgba(148,163,184,0.08)",
      glowA: `${theme.accentLight}24`,
      glowB: `${theme.accentLight}1f`,
      badgeBg: theme.accent,
      badgeText: "#ffffff",
      pleaseNoteBg: `${theme.accentLight}14`,
      pleaseNoteText: theme.accentLight,
      ecoIconBg: "rgba(255,255,255,0.08)",
      ecoIcon: theme.accentLight,
      ecoLabel: "#94a3b8",
      infoShadow: "0 10px 30px rgba(0,0,0,0.45)",
      ctaSoft: "rgba(255,255,255,0.12)",
      ctaSoftBorder: "rgba(255,255,255,0.3)",
    };
  }

  if (tpl.minimal) {
    t = {
      ...t,
      bgColor: "#fafafa",
      bg: "linear-gradient(180deg, #fafafa 0%, #f2f2f2 100%)",
      title: "#111111",
      body: "#3f3f46",
      label: "#71717a",
      value: "#18181b",
      sectionHeader: "#18181b",
      cardBg: "#ffffff",
      cardBorder: "#e4e4e7",
      cardShadow: "none",
      infoBg: "#ffffff",
      infoBorder: "#e4e4e7",
      infoShadow: "none",
      chipBg: "transparent",
      chipBorder: "#d4d4d8",
      chipText: "#3f3f46",
      tileA: theme.accentDark,
      tileAIcon: "#ffffff",
      tileB: "#f4f4f5",
      tileBBorder: "#d4d4d8",
      tileBIcon: "#18181b",
      dots: "rgba(0,0,0,0.05)",
      glowA: "transparent",
      glowB: "transparent",
      pleaseNoteBg: "#f4f4f5",
      pleaseNoteText: theme.accentDark,
      ecoIconBg: "#f4f4f5",
      ecoIcon: theme.accentDark,
      ecoLabel: "#52525b",
    };
  }

  if (tpl.executive) {
    t = {
      ...t,
      bg: `linear-gradient(180deg, #ffffff 0%, ${theme.bgSoft} 100%)`,
      cardShadow: "0 10px 28px rgba(15,23,42,0.07)",
      cardBorder: theme.accentBorder,
      chipBg: theme.accentSoft,
      tileB: theme.accentSoft,
      tileBBorder: theme.accentBorder,
    };
  }

  if (tpl.borderless) {
    t = {
      ...t,
      bg: `linear-gradient(180deg, #ffffff 0%, ${theme.bgSoft} 100%)`,
      cardBg: `${theme.accentSoft}66`,
      cardBorder: "none",
      cardShadow: "none",
      infoShadow: "none",
      infoBg: "transparent",
      infoBorder: "none",
      chipBg: theme.accentSoft,
      chipBorder: "none",
      tileBBorder: "none",
      tileB: "#ffffff",
    };
  }

  if (tpl.banner) {
    t = {
      ...t,
      showTopBar: false,
      infoBg: "#ffffff",
      infoBorder: "#e2e8f0",
      infoShadow: "0 8px 24px rgba(0,0,0,0.06)",
      cardBg: "#ffffff",
      cardBorder: "#e2e8f0",
      cardShadow: "0 10px 30px rgba(15,23,42,0.06)",
      bannerTitle: "#ffffff",
      bannerEyebrowBg: "rgba(255,255,255,0.16)",
      bannerEyebrowText: theme.bgSoft,
      bannerChipBg: "rgba(255,255,255,0.14)",
      bannerChipBorder: "rgba(255,255,255,0.4)",
      bannerChipText: "#ffffff",
    };
  }

  if (tpl.corporate) {
    // EMC corporate flyer: crisp white bg + simultaneous navy/red/green grading.
    t = {
      ...t,
      bgColor: "#ffffff",
      bg: "linear-gradient(180deg, #ffffff 0%, #f4f7fb 100%)",
      title: "#0a1128",
      body: "#2b2f36",
      label: "#64748b",
      value: "#0a1128",
      sectionHeader: "#ffffff",
      cardBg: "#ffffff",
      cardBorder: "#dbe1ea",
      cardShadow: "0 10px 30px rgba(10,17,40,0.08)",
      chipBg: "#eef2ff",
      chipBorder: "#c7d2fe",
      chipText: "#1b3167",
      markerA: "#e63946",
      markerB: "#e63946",
      dots: "rgba(27,49,103,0.05)",
      glowA: "transparent",
      glowB: "transparent",
      infoShadow: "none",
      pleaseNoteBg: "#1b3167",
      pleaseNoteText: "#ffffff",
      ecoIconBg: "#eef2ff",
      ecoIcon: "#1b3167",
      ecoLabel: "#475569",
      badgeBg: "#ffffff",
      badgeText: "#0a1128",
      tileA: "linear-gradient(135deg, #14532d, #16a34a)",
      tileAIcon: "#ffffff",
      tileB: "#eef2ff",
      tileBBorder: "#c7d2fe",
      tileBIcon: "#1b3167",
    };
  }

  if (tpl.hiring) {
    // Flyer 7 (Manager, Retail Sales): light blue tint, charcoal ribbon, red title.
    t = {
      ...t,
      bgColor: "#f2f7fd",
      bg: "linear-gradient(180deg, #f5f9fe 0%, #e9f1fb 100%)",
      title: "#b91c1c",
      body: "#374151",
      label: "#64748b",
      value: "#111827",
      sectionHeader: "#111827",
      cardBg: "#ffffff",
      cardBorder: "#dbe4f0",
      cardShadow: "0 10px 30px rgba(15,42,92,0.07)",
      chipBg: "#ffffff",
      chipBorder: "#dbe4f0",
      chipText: "#111827",
      markerA: "#dc2626",
      markerB: "#dc2626",
      dots: "rgba(30,58,138,0.05)",
      glowA: "rgba(37,99,235,0.07)",
      glowB: "rgba(220,38,38,0.05)",
      badgeBg: "#1f2937",
      badgeText: "#ffffff",
      pleaseNoteBg: "#eef2ff",
      pleaseNoteText: "#1e40af",
      ecoIconBg: "#ffffff",
      ecoIcon: "#1f2937",
      ecoLabel: "#475569",
      infoBg: "#ffffff",
      infoBorder: "#dbe4f0",
      infoShadow: "0 8px 24px rgba(15,42,92,0.06)",
    };
  }

  if (tpl.darkCard) {
    // Flyer 6 (Corporate Accountant): dark green page + centered white card.
    t = {
      ...t,
      bgColor: "#0b1a12",
      bg: "linear-gradient(180deg, #0b1a12 0%, #123021 100%)",
      title: "#111827",
      body: "#374151",
      label: "#6b7280",
      value: "#111827",
      sectionHeader: "#111827",
      cardBg: "#ffffff",
      cardBorder: "#e5e7eb",
      cardShadow: "0 20px 60px rgba(0,0,0,0.45)",
      chipBg: "#fdf2f8",
      chipBorder: "#fbcfe8",
      chipText: "#9d174d",
      markerA: "#9d174d",
      markerB: "#9d174d",
      dots: "rgba(0,0,0,0.04)",
      glowA: "transparent",
      glowB: "transparent",
      badgeBg: "#111827",
      badgeText: "#ffffff",
      pleaseNoteBg: "#f3f4f6",
      pleaseNoteText: "#111827",
      ecoIconBg: "rgba(255,255,255,0.12)",
      ecoIcon: "#ffffff",
      ecoLabel: "#d1fae5",
      infoBg: "#ffffff",
      infoBorder: "#e5e7eb",
      infoShadow: "0 8px 24px rgba(0,0,0,0.08)",
    };
  }

  if (tpl.splitDark) {
    // Flyer 3 (Country Manager): light field + navy diagonal split, logo on dark.
    t = {
      ...t,
      bgColor: "#eef1f6",
      bg: "linear-gradient(180deg, #f2f4f8 0%, #e7ebf2 100%)",
      title: "#0f1b3d",
      body: "#2f3646",
      label: "#5b6478",
      value: "#0f1b3d",
      sectionHeader: "#0f1b3d",
      cardBg: "#ffffff",
      cardBorder: "#dde3ec",
      cardShadow: "0 10px 30px rgba(15,27,61,0.08)",
      chipBg: "#ffffff",
      chipBorder: "#dde3ec",
      chipText: "#0f1b3d",
      markerA: "#1b3167",
      markerB: "#e63946",
      dots: "rgba(15,27,61,0.05)",
      glowA: "transparent",
      glowB: "transparent",
      badgeBg: "#1b3167",
      badgeText: "#ffffff",
      pleaseNoteBg: "#ffffff",
      pleaseNoteText: "#1b3167",
      ecoIconBg: "#ffffff",
      ecoIcon: "#1b3167",
      ecoLabel: "#475569",
      infoBg: "#ffffff",
      infoBorder: "#dde3ec",
      infoShadow: "0 8px 24px rgba(15,27,61,0.07)",
    };
  }

  return t;
}
